title: Arduino Programming
description: This website contains learning materials for Arduino Programming component of CT1111 Engineering Computing module taught to 1st year engineering students at University of Galway.
theme: just-the-docs

url: https://adnanelahi.github.io/CT1111

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
